### ISSUE TITLE
Color of state confusing in Dark Mode

### ISSUE THREAD

**Issue by TLongstride** [JuanMTech/ios-theme#2]
Hi,

I got an issue with the color of icon and there state.

In the Light theme : ON = Blue ; OFF = Grey that's OK

In the Dark theme : ON = Grey ; OFF = Blue that's not OK, with the auto switch mode, that's confusing !

And in default theme, ON = Yellow, OFF = Light Blue, Unaivaillable = Grey 

Could this theme act as the defaut theme for the color of the button ? That would be great and not confusing !

Thanks
Thomas

**Comment by T-bond** [comment]
For me the colors are correct on the first tab. And only swapped on the other tabs.

First tab:
![image](https://user-images.githubusercontent.com/3778556/159001427-aef03d51-20f4-46b0-af19-e9478339e3a2.png)
Second tab (and other tabs too):
![image](https://user-images.githubusercontent.com/3778556/159001471-a2869ccc-171f-47fd-847b-f6a066acc17d.png)
(Both light are turned off)

I think it was working before I upgraded to 2022.3.5, and it was also working at 2022.3.0. So maybe it is a lovelace bug?

Also on the Light theme, it does not seems to be swapped, as the original report says too.

Maybe related: https://github.com/home-assistant/frontend/issues/12057

Update: The solution on the previously linked issue works for me. So I think this is not a bug in the theme.

**Comment by JuanMTech** [comment]
I was not able to replicate the same issue.
